apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
  labels:
    app: spring-demo
spec:
  replicas: 1
  selector:
        matchLabels:
                app: spring-demo
  template:
    metadata:
      name: spring-demo
      labels:
        app: spring-demo
    spec:
      containers:
        - image: sptest
          imagePullPolicy: IfNotPresent
          name: spring-demo
